.\" swim - simple window manager
.\" Copyright (C) 2022 ArcNyxx
.\" see LICENCE file for licensing information
.TH SWIM 1 swim\-VERSION
.SH NAME
swim \- simple window manager
.SH SYNOPSIS
.SY swim
.YS
.SH DESCRIPTION
.BR swim (1)
is a quick and tiny window manager for X.  It manages windows in a tiled layout
with each side of each screen allocated to master and stacking windows
respectively.  Clients are grouped by selecting tags, and can be viewed by
selecting these tags.
.SH AUTHOR
Written by
.BR dwm (1)
contributors and ArcNyxx.
.SH SEE ALSO
.BR dwm (1),\  st (1)
