.\" swim - simple window manager
.\" Copyright (C) 2022 ArcNyxx
.\" see LICENCE file for licensing information
.TH SWIM 1 swim\-VERSION
.SH NAME
swim \- simple window manager
.SH SYNOPSIS
.SY swim
.YS
.SH DESCRIPTION
.BR swim (1)
is a quick and tiny window manager for X.  It manages windows in a tiled layout
with each side of each screen allocated to master and stacking windows
respectively.  Clients are grouped by selecting tags, and can be viewed by
selecting these tags.
.SH CONFIGURATION
.BR swim (1)
can be configured by editing the generated config.h file and (re)compiling the
source code.  This keeps it fast, simple, and secure.
.SH AUTHOR
Written by
.BR dwm (1)
contributors and ArcNyxx.
.SH SEE ALSO
.BR dwm (1),\  st (1)
.SH BUGS
Send all bug reports to the main development branch of
.BR swim (1),
which can be found at
.UR https://github.com/arcnyxx/swim
ArcNyxx's GitHub page
.UE .
